apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sec-manager
  template:
    metadata:
      labels:
        app: sec-manager
    spec:
      containers:
      - name: sec-manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: sec-manager-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sec-manager
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http