version: "3.9"  # Docker Compose file format version

services:
  data_collector:
    build:
      context: ./services/data-collector
      dockerfile: Dockerfile
    container_name: data_collector
    environment:
      - ENV=production
      # add any additional environment variables here
    ports:
      - "8001:8000"
    volumes:
      - ./services/data-collector/src:/app/src
    command: python src/main.py

  etl_manager:
    build:
      context: ./services/etl-manager
      dockerfile: Dockerfile
    container_name: etl_manager
    environment:
      - ENV=production
    ports:
      - "8002:8000"
    volumes:
      - ./services/etl-manager/src:/app/src
    command: python src/main.py

  forecast_engine:
    build:
      context: ./services/forecast-engine
      dockerfile: Dockerfile
    container_name: forecast_engine
    environment:
      - ENV=production
    ports:
      - "8003:8000"
    volumes:
      - ./services/forecast-engine/src:/app/src
    command: python src/main.py

  fin_dash:
    build:
      context: ./services/fin-dash
      dockerfile: Dockerfile
    container_name: fin_dash
    environment:
      - ENV=production
    ports:
      - "8004:8000"
    volumes:
      - ./services/fin-dash/src:/app/src
    command: python src/main.py

  sec_manager:
    build:
      context: ./services/sec-manager
      dockerfile: Dockerfile
    container_name: sec_manager
    environment:
      - ENV=production
    ports:
      - "8005:8000"
    volumes:
      - ./services/sec-manager/src:/app/src
    command: python src/main.py