apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - name: data-collector
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: data-collector
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http