apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecast-engine
  template:
    metadata:
      labels:
        app: forecast-engine
    spec:
      containers:
      - name: forecast-engine
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: forecast-engine-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: forecast-engine
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http